"use client";

import {useEffect, useRef, useState} from "react";

// The peaks are pre-generated by audiowaveform at build time, so drawing them is
// a canvas loop over an array - no audio decoding, no library, no main-thread
// stall when the track changes.
export function Waveform({
  bounceUlid,
  progress,
  onSeek,
  accent,
}: {
  bounceUlid: string;
  progress: number;
  onSeek: (fraction: number) => void;
  accent?: string;
}) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [peaks, setPeaks] = useState<number[] | null>(null);
  const growth = useRef(0);
  const raf = useRef(0);
  const [tick, setTick] = useState(0);

  useEffect(() => {
    let live = true;
    setPeaks(null);
    growth.current = 0;
    fetch(`/peaks/${bounceUlid}`, {credentials: "same-origin"})
      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
      .then((data) => {
        if (!live) return;
        const raw: number[] = Array.isArray(data) ? data : (data.data ?? []);
        setPeaks(raw);
      })
      .catch(() => {
        if (live) setPeaks(null);
      });
    return () => {
      live = false;
    };
  }, [bounceUlid]);

  // A size change must trigger a redraw: the first draw can land before layout
  // settles (a ~40px-wide canvas), and with nothing else changing that stale
  // buffer stays on screen — the squeezed ghost wave at the left edge.
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const observer = new ResizeObserver(() => setTick((n) => n + 1));
    observer.observe(canvas);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const box = canvas.getBoundingClientRect();
    if (box.width < 2) return;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.max(1, Math.floor(box.width * dpr));
    canvas.height = Math.max(1, Math.floor(box.height * dpr));
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.scale(dpr, dpr);

    if (!peaks || !peaks.length) {
      ctx.fillStyle = "rgba(255,255,255,.1)";
      ctx.fillRect(0, box.height / 2 - 1, box.width, 2);
      return;
    }

    // audiowaveform emits interleaved min/max pairs; take the magnitude.
    const bars = Math.max(1, Math.floor(box.width / 3));
    const stride = Math.max(1, Math.floor(peaks.length / bars));
    let peak = 1;
    for (let i = 0; i < peaks.length; i += 1) {
      const v = Math.abs(peaks[i]);
      if (v > peak) peak = v;
    }

    const played = Math.round(bars * progress);
    for (let i = 0; i < bars; i += 1) {
      let magnitude = 0;
      for (let j = 0; j < stride; j += 1) {
        const value = Math.abs(peaks[i * stride + j] ?? 0);
        if (value > magnitude) magnitude = value;
      }
      const height = Math.max(2, (magnitude / peak) * (box.height - 2) * growth.current);
      ctx.fillStyle =
        i <= played ? (accent || "rgba(255,255,255,.92)") : "rgba(255,255,255,.2)";
      ctx.fillRect(i * 3, (box.height - height) / 2, 2, height);
    }
  }, [peaks, progress, accent, tick]);

  // Bars rise once when a track loads. Redrawing on every frame of a 240ms ease
  // is cheap here because the whole render is one canvas loop.
  useEffect(() => {
    if (!peaks) return;
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const duration = reduced ? 90 : 260;
    let start = 0;
    const step = (now: number) => {
      if (!start) start = now;
      const t = Math.min(1, (now - start) / duration);
      growth.current = 1 - Math.pow(1 - t, 3);
      setTick((n) => n + 1);
      if (t < 1) raf.current = requestAnimationFrame(step);
    };
    raf.current = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf.current);
  }, [peaks]);

  return (
    <canvas
      ref={canvasRef}
      className="wave"
      onClick={(event) => {
        const box = event.currentTarget.getBoundingClientRect();
        onSeek((event.clientX - box.left) / box.width);
      }}
    />
  );
}
